Work section
theodoku/Project_Portfolio pull request #2
Opened 2022-11-03 17:26 UTC by theodoku

Works section of Project portfolio - mobile first

2022-11-03 18:16 UTC, OyePriscilla requested changes
Hi @theodoku   😃 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Good commits messages ✔️ 
GitHub flow observed ✔️ 
Linters checks passed ✔️ 

## Required Changes ♻️

- [ ] Kindly add a more descriptive PR summary. 

## Optional suggestions

- [optional] Please ensure that your subsequent commit messages are in sentence case.

- [optional]  For subsequent PR, kindly ensure that your branch name speaks to the activity you're doing. I could see `testbranch `for this PR. This is not so right, it can be confusing.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 18:16 UTC, OyePriscilla commented on index.html
> +                <p id="connect1"> LET'S CONNECT</p>
- [ ] Please take note of this as well, it should either be a link `a `tag or `button `tag, because it must be clickable to trigger an event. 😃

2022-11-03 18:16 UTC, OyePriscilla commented on index.html
> +                <p id="resume">Get my resume</p>
- [ ] Please take note of this as well, it should either be a link `a `tag or `button `tag, because it must be clickable to trigger an event. 😃

2022-11-03 18:16 UTC, OyePriscilla commented on index.html
> +                    <div class="project-title1">
- [ ] Please note that according to the requirement you suppose to display this section `works_section `as grid. Please Kindly effect this. 👍

2022-11-03 18:16 UTC, OyePriscilla commented on index.html
> +                        </ul>
- [ ] Please use class selector instead of Id. You can revisit  [HTML/CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) for confirmation (No. 10). 👍

2022-11-04 00:08 UTC, theodoku commented on index.html
> +                    </div>
list of technologies have been wrapped in a ul

2022-11-04 00:11 UTC, theodoku commented on index.html
> +                        <p id="view1">See Project</p>
solved

2022-11-04 00:11 UTC, theodoku commented on index.html
> +                <p id="connect1"> LET'S CONNECT</p>
updated

2022-11-04 00:12 UTC, theodoku commented on index.html
> +                <p id="resume">Get my resume</p>
updated

2022-11-04 00:13 UTC, theodoku commented on index.html
> +                    <div class="project-title1">
work section changed to grid

2022-11-04 00:13 UTC, theodoku commented on index.html
> +                        </ul>
updated

2022-11-04 01:10 UTC, fherrerao requested changes
Hi @theodoku, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![So Close Snl GIF by Saturday Night Live](https://user-images.githubusercontent.com/91301423/197784121-950974af-5415-4bf0-871b-ce226a51ace4.gif)
 ## Highlights

✔️  No linter errors.
✔️  You used the correct GitHub-Flow.
✔️  Good README
✔️  Good Commit Messages

 ## Required Changes ♻️

- [ ] Excellent job making changes required for the previous reviewer 💯, but I think you forgot to add a more descriptive PR summary as requested by @OyePriscilla. 🥇, please modify it.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 08:56 UTC, theodoku commented
- Created a new branch called the 'works section'.
- Added 'About Myself' to the section
- Review programming language best practices
- Made changes where it does not align with best practices

2022-11-04 09:05 UTC, emmiiorji approved these changes
Hi @theodoku, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Red-approved](https://user-images.githubusercontent.com/20554583/199362837-208e4c72-b63b-4cdb-a8ed-cebfdac94960.gif)

## Good Highlights

- Linter checks are passing
- Adherence to GitHub flow
- Repo is professional
- Good commit messages


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 09:31 UTC, merged